SELECT A.EMP_NO, A.EMP_NAME, (
CASE 
    WHEN AVG_SCORE>=96 THEN "S"
    WHEN AVG_SCORE >= 90 AND AVG_SCORE <96 THEN "A"
    WHEN AVG_SCORE>=80 AND AVG_SCORE<90 THEN "B"
    ELSE "C"
    END
) AS GRADE, (
CASE
    WHEN AVG_SCORE>=96 THEN A.SAL * 0.2
    WHEN AVG_SCORE >= 90 AND AVG_SCORE <96 THEN A.SAL * 0.15
    WHEN AVG_SCORE>=80 AND AVG_SCORE<90 THEN A.SAL * 0.1
    ELSE 0
    END
) AS BONUS
FROM HR_EMPLOYEES A JOIN (
SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
FROM HR_GRADE
GROUP BY EMP_NO) B ON A.EMP_NO = B.EMP_NO
ORDER BY A.EMP_NO ASC