# -- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, B.MAX_LEN AS LENGTH
FROM FISH_INFO AS A JOIN 
(
SELECT A.FISH_TYPE, MAX_LEN, FISH_NAME
FROM(
SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
FROM FISH_INFO
GROUP BY FISH_TYPE) AS A JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE) AS B
ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.MAX_LEN
ORDER BY A.ID

