SELECT C.SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_DEPARTMENT A JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
     FROM HR_GRADE
     WHERE YEAR = '2022'
     GROUP BY EMP_NO) C ON B.EMP_NO = C.EMP_NO
GROUP BY B.EMP_NO
ORDER BY C.SCORE DESC
LIMIT 1
